import "../globals.css";

export const metadata = {
  title: "NextLevel Food",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="p-12">{children}</body>
    </html>
  );
}
