import "./globals.css";

export const metadata = {
  title: "Udemy NextJS Tutorial",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="p-10">{children}</body>
    </html>
  );
}
