export const DUMMY_NEWS = [
  {
    id: "n1",
    slug: "asian-food",
    title: "Asian Food",
    image: "asian-food.jpg",
    date: "2023-06-01",
    content: "This is a sample news item about Asian food.",
  },
  {
    id: "n2",
    slug: "japanese-food",
    title: "Japanese Food",
    image: "japan-food.jpg",
    date: "2024-10-02",
    content: "This is a sample news item about Japanese food.",
  },
  {
    id: "n3",
    slug: "italian-food",
    title: "Italian Food",
    image: "italian-food.jpg",
    date: "2022-08-01",
    content: "This is a sample news item about Italian food.",
  },
  {
    id: "n4",
    slug: "italian-food",
    title: "Italian Food",
    image: "italian-food.jpg",
    date: "2023-09-20",
    content: "This is a sample news item about Italian food.",
  },
  {
    id: "n5",
    slug: "japanese-food",
    title: "Japanese Food",
    image: "japan-food.jpg",
    date: "2024-12-20",
    content: "This is a sample news item about Japanese food.",
  },
];
